import 'package:cloud_firestore/cloud_firestore.dart';

class Delivery {
  final String id;
  final String orderNumber;
  final String clinicName;
  final String clinicAddress;
  final String vaccineName;
  final String? vaccineType;
  final int quantity;
  final String unit;
  final String priority;
  final String status;
  final String statusLabel;
  final String? region;
  final String? deliveryInstructions;
  final String? assignedRiderId;
  final String? assignedRiderName;
  final String? proofOfDeliveryUrl;
  final String? invoiceUrl;
  final List<String> itemSummaries;
  final DateTime? createdAt;
  final DateTime? assignedAt;
  final DateTime? startedAt;
  final DateTime? deliveredAt;
  final DateTime? updatedAt;
  final GeoPoint? lastLocation;

  // Manual clinic coordinates (copied from the clinic at order creation) and the
  // route/ETA generated by the web Dispatcher (OpenRouteService). All optional —
  // orders from coord-less clinics, or before a dispatcher generates a route,
  // simply omit these. The Rider app only READS these; it never writes them.
  final double? clinicLat;
  final double? clinicLng;
  final String? routePolyline; // encoded polyline (precision 5)
  final int? routeDistanceMeters;
  final int? routeDurationSeconds;
  final String? routeEtaText;
  final DateTime? routeGeneratedAt;

  Delivery({
    required this.id,
    required this.orderNumber,
    required this.clinicName,
    required this.clinicAddress,
    required this.vaccineName,
    this.vaccineType,
    required this.quantity,
    required this.unit,
    required this.priority,
    required this.status,
    required this.statusLabel,
    this.region,
    this.deliveryInstructions,
    this.assignedRiderId,
    this.assignedRiderName,
    this.proofOfDeliveryUrl,
    this.invoiceUrl,
    this.itemSummaries = const [],
    this.createdAt,
    this.assignedAt,
    this.startedAt,
    this.deliveredAt,
    this.updatedAt,
    this.lastLocation,
    this.clinicLat,
    this.clinicLng,
    this.routePolyline,
    this.routeDistanceMeters,
    this.routeDurationSeconds,
    this.routeEtaText,
    this.routeGeneratedAt,
  });

  factory Delivery.fromFirestore(String docId, Map<String, dynamic> data) {
    final rawStatus = _getStatus(data);
    final normalizedStatus = _normalizeStatus(rawStatus);

    return Delivery(
      id: docId,
      orderNumber: data['orderNumber'] ?? docId,
      clinicName: data['clinicName'] ?? 'Unknown Clinic',
      clinicAddress: data['clinicAddress'] ?? '',
      vaccineName: data['vaccineName'] ?? '',
      vaccineType: data['vaccineType'],
      quantity: _toQuantity(data['quantity']) ?? 0,
      unit: data['unit'] ?? 'vials',
      priority: data['priority'] ?? 'Standard',
      status: normalizedStatus,
      statusLabel: _statusLabel(normalizedStatus),
      region: data['region'],
      deliveryInstructions: data['deliveryInstructions'],
      assignedRiderId: data['assignedRiderId'],
      assignedRiderName: data['assignedRiderName'],
      proofOfDeliveryUrl: data['proofOfDeliveryUrl'],
      invoiceUrl: data['invoiceUrl'],
      itemSummaries: _itemSummaries(data['items']),
      createdAt: _toDateTime(data['createdAt']),
      assignedAt: _toDateTime(data['assignedAt']),
      startedAt: _toDateTime(data['startedAt']),
      deliveredAt: _toDateTime(data['deliveredAt']),
      updatedAt: _toDateTime(data['updatedAt']),
      lastLocation: data['lastLocation'] as GeoPoint?,
      clinicLat: _toDouble(data['clinicLat']),
      clinicLng: _toDouble(data['clinicLng']),
      routePolyline: (data['routePolyline'] as String?)?.isEmpty ?? true
          ? null
          : data['routePolyline'] as String?,
      routeDistanceMeters: _toInt(data['routeDistanceMeters']),
      routeDurationSeconds: _toInt(data['routeDurationSeconds']),
      routeEtaText: data['routeEtaText'] as String?,
      routeGeneratedAt: _toDateTime(data['routeGeneratedAt']),
    );
  }

  /// True when the order carries finite clinic coordinates.
  bool get hasClinicCoords => clinicLat != null && clinicLng != null;

  /// True when a decodable route + distance were saved by the dispatcher.
  bool get hasRoute =>
      routePolyline != null && (routeDistanceMeters ?? 0) > 0;

  static double? _toDouble(dynamic value) {
    if (value is num) {
      final d = value.toDouble();
      return d.isFinite ? d : null;
    }
    return null;
  }

  /// Numeric coercion for `orders.quantity`.
  ///
  /// The previous `(data['quantity'] ?? 0).toInt()` assumed the field was
  /// always a `num`. It is not: legacy / hand-seeded orders can carry it as a
  /// STRING. The observed case was staging order **VT-STG-001**, which held a
  /// string quantity of `"10"`; the Rider app failed with
  /// `NoSuchMethodError: Class 'String' has no instance method 'toInt'.
  /// Receiver: "10"`, which escaped the snapshot mapping and blanked the
  /// rider's ENTIRE delivery list — including the four well-formed orders
  /// alongside it. Correcting that one document's field type to a number
  /// restored the list, confirming the diagnosis. (That document has since
  /// been corrected; this guard is what stops the next one recurring.)
  ///
  /// A non-finite `num` (`double.infinity` / `double.nan`) was the second,
  /// unhit branch of the same defect: `.toInt()` on those throws
  /// `Unsupported operation: Infinity or NaN toInt`.
  ///
  /// Normalizes what is genuinely a quantity — an int, a finite num, or a
  /// numeric string — and returns `null` for anything else so the caller falls
  /// back to the pre-existing `0` default. It never guesses a quantity from a
  /// value that does not contain one.
  static int? _toQuantity(dynamic value) {
    if (value is int) return value;
    if (value is num) return value.isFinite ? value.toInt() : null;
    if (value is String) {
      final text = value.trim();
      if (text.isEmpty) return null;
      final asInt = int.tryParse(text);
      if (asInt != null) return asInt;
      final asDouble = double.tryParse(text);
      if (asDouble != null && asDouble.isFinite) return asDouble.toInt();
    }
    return null;
  }

  /// Same non-finite guard as [_toDouble] — `double.infinity.toInt()` throws
  /// `Unsupported operation: Infinity or NaN toInt`, so a corrupt route field
  /// could crash the mapping exactly like `quantity` did.
  static int? _toInt(dynamic value) {
    if (value is num) return value.isFinite ? value.toInt() : null;
    return null;
  }

  static List<String> _itemSummaries(dynamic items) {
    if (items is! List) return const [];
    return items
        .whereType<Map>()
        .map((item) {
          final name = (item['vaccineName'] ?? item['name'] ?? '').toString();
          if (name.isEmpty) return '';
          final qty = item['quantity'];
          final unit = (item['unit'] ?? 'vials').toString();
          return qty == null ? name : '$name — $qty $unit';
        })
        .where((s) => s.isNotEmpty)
        .toList();
  }

  bool get isDelivered => status == 'delivered' || status == 'completed';
  bool get isInTransit => status == 'in_transit';
  bool get isLoading => status == 'loading';
  bool get isAssigned => status == 'assigned';
  bool get isDelayed => status == 'delayed';
  bool get isCancelled => status == 'cancelled' || status == 'canceled';
  bool get isActive => !isDelivered && !isCancelled;
  bool get isUrgent => priority == 'Urgent' && !isDelivered;
  bool get canStartLoading => status == 'assigned';
  bool get canStartTransit => status == 'loading';
  bool get canDeliver => status == 'in_transit';

  static String _getStatus(Map<String, dynamic> data) {
    return (data['status'] ??
            data['orderStatus'] ??
            data['deliveryStatus'] ??
            data['shipmentStatus'] ??
            data['dispatchStatus'] ??
            'pending')
        .toString();
  }

  static String _normalizeStatus(String raw) {
    return raw.trim().toLowerCase().replaceAll('-', '_').replaceAll(RegExp(r'\s+'), '_');
  }

  static String _statusLabel(String status) {
    switch (status) {
      case 'pending':
      case 'pending_dispatch':
        return 'Pending';
      case 'assigned':
        return 'Assigned';
      case 'loading':
        return 'Loading';
      case 'in_transit':
        return 'In Transit';
      case 'delivered':
      case 'completed':
        return 'Delivered';
      case 'delayed':
        return 'Delayed';
      case 'cancelled':
      case 'canceled':
        return 'Cancelled';
      default:
        return 'Pending';
    }
  }

  static DateTime? _toDateTime(dynamic value) {
    if (value is Timestamp) return value.toDate();
    if (value is DateTime) return value;
    return null;
  }
}
