"use strict";

/**
 * Invoice base pricing, derived from an order's immutable snapshot.
 *
 * Pure: no Firestore, no Functions SDK. Everything that decides what an invoice
 * line COSTS lives here, so it is unit-testable without an emulator, and so
 * there is exactly one implementation of the arithmetic rather than one on each
 * side of the wire.
 *
 * THE AUTHORITY BOUNDARY
 *   Base pricing — item identity, quantity, unitPriceCentavos, lineTotalCentavos,
 *   subtotalCentavos and currency — comes from the ORDER's snapshot and from
 *   nowhere else; the VAT rate and the VAT-inclusive convention come from
 *   pricingConfig.js. The caller cannot supply, override or influence any of it.
 *
 *   Adjustments — discount, other charges, withholding tax and the VAT
 *   classification — are genuinely the admin's decision, so they ARE accepted
 *   from the caller. They are separate fields that sit alongside the base and
 *   can never overwrite it: a discount reduces the net, it does not restate what
 *   a vial cost.
 *
 * Legacy orders (no pricingVersion) never reach this module. They keep the
 * manual invoice-time pricing they have always had.
 */

const {
  PRICING_VERSION,
  PRICE_CURRENCY,
  PolicyError,
  readProductVatClassification,
} = require("./policy");
const { VAT_RATE_PERCENT, PRICES_INCLUDE_VAT, splitVatInclusiveCentavos } = require("./pricingConfig");

/** Philippine VAT, from the one pricing configuration (pricingConfig.js). */
const VAT_STANDARD_RATE = VAT_RATE_PERCENT;
const VAT_CLASSIFICATIONS = Object.freeze(["vatable", "vat_exempt", "zero_rated"]);

/**
 * The invoice-level marker for an order whose EVERY item carries a VAT
 * snapshot. Its VAT comes from those items, not from an Admin choice: VATable
 * and VAT-Exempt sales are summed per line, an invoice discount is split
 * between them pro-rata (see allocateDiscountCentavos), and the 12% VAT is
 * EXTRACTED from the discounted, VAT-inclusive VATable sales only — never added
 * on top (pricingConfig.js). Orders without item snapshots keep the Admin's
 * invoice-level classification, which must be chosen explicitly.
 */
const ITEMIZED_VAT = "per_item";

/**
 * Free-text fields an admin genuinely owns.
 *
 * An allowlist rather than a denylist: a new field added to the editor must be
 * named here deliberately, so a caller can never smuggle `subtotalCentavos`
 * through as "presentation" simply because nobody thought to forbid it.
 */
const PRESENTATION_FIELDS = Object.freeze([
  "customerName", "registeredName", "customerAddress", "customerContact",
  "customerTin", "customerCode", "shipTo",
  "salesRepName", "salesRepCode",
  "invoiceDate", "saleType", "purchaseOrderNumber", "referenceNumber",
  "companyName", "companyAddress", "companyContact", "companyTin",
  "paymentTerms", "deliveryTerms", "notes", "remarks",
  "processedBy", "packedBy", "deliveredBy", "preparedBy", "checkedBy",
  "approvedBy", "receivedBy", "authorizedRepresentative",
  "customerAcknowledgment", "soloParentId", "bookletInfo",
  "atpNumber", "atpDate", "printerBlock", "accreditationNo", "accreditationDates",
]);

const MAX_PRESENTATION_LENGTH = 500;

/** An order whose prices were generated by the server. Version stamp only. */
function isServerPricedOrder(order) {
  return order?.pricingVersion === PRICING_VERSION;
}

/** A stored money figure: an exactly-representable non-negative integer. */
function readCentavos(value) {
  return (
    typeof value === "number" &&
    Number.isInteger(value) &&
    Number.isSafeInteger(value) &&
    value >= 0
  );
}

function centavosToPesos(centavos) {
  return Math.round(centavos) / 100;
}

/**
 * The invoice's base pricing, computed from the order snapshot.
 *
 * Every figure is RE-DERIVED here and cross-checked against what the order
 * recorded, so a corrupted order document produces a refusal rather than a
 * plausible-looking invoice. Nothing in the returned object came from a caller.
 */
function buildInvoiceBaseFromOrder(order) {
  if (!isServerPricedOrder(order)) {
    throw new PolicyError(
      "order-not-priced",
      "This order has no server price snapshot. It is invoiced through the manual path."
    );
  }
  const orderItems = Array.isArray(order.items) ? order.items : [];
  if (orderItems.length === 0) {
    throw new PolicyError(
      "order-has-no-items",
      "This order has no items to invoice."
    );
  }

  let subtotalCentavos = 0;
  const items = orderItems.map((it, index) => {
    const quantity = it?.quantity;
    if (typeof quantity !== "number" || !Number.isInteger(quantity) || quantity <= 0) {
      throw new PolicyError("order-snapshot-invalid", "This order's quantities cannot be invoiced.", {
        line: index,
      });
    }
    if (!readCentavos(it?.unitPriceCentavos) || it.unitPriceCentavos <= 0) {
      throw new PolicyError("order-snapshot-invalid", "This order's prices cannot be invoiced.", {
        line: index,
      });
    }
    // Recomputed, then compared with what the order stored. Trusting the stored
    // line total would let a single tampered field flow straight onto a bill.
    const lineTotalCentavos = quantity * it.unitPriceCentavos;
    if (!Number.isSafeInteger(lineTotalCentavos)) {
      throw new PolicyError("order-snapshot-invalid", "This order's totals are out of range.", {
        line: index,
      });
    }
    if (it.lineTotalCentavos !== lineTotalCentavos) {
      throw new PolicyError(
        "order-snapshot-invalid",
        "This order's line totals do not match its prices and quantities.",
        { line: index }
      );
    }
    subtotalCentavos += lineTotalCentavos;

    return {
      // Identity, carried through so an invoice line is traceable to a batch.
      orderItemId: null,
      inventoryId: typeof it.inventoryId === "string" ? it.inventoryId : null,
      batchId: typeof it.batchId === "string" ? it.batchId : "",
      vaccineName: typeof it.name === "string" ? it.name : "",
      itemDescription: typeof it.name === "string" ? it.name : "",
      expiry: "",
      quantity,
      unit: typeof order.unit === "string" && order.unit ? order.unit : "vials",
      unitPriceCentavos: it.unitPriceCentavos,
      lineTotalCentavos,
      // The order item's immutable VAT snapshot, or null on an order created
      // before snapshots existed. Never inferred from the product's current value.
      vatClassification: readProductVatClassification(it?.vatClassification),
      // Peso mirrors for the print template, derived — never authoritative.
      unitPrice: centavosToPesos(it.unitPriceCentavos),
      amount: centavosToPesos(lineTotalCentavos),
    };
  });

  if (!Number.isSafeInteger(subtotalCentavos)) {
    throw new PolicyError("order-snapshot-invalid", "This order's subtotal is out of range.");
  }
  // The order recorded its own subtotal at reservation time. If the two ever
  // disagree, something rewrote one of them and neither can be trusted.
  if (order.subtotalCentavos !== subtotalCentavos) {
    throw new PolicyError(
      "order-snapshot-invalid",
      "This order's subtotal does not match its line items."
    );
  }

  return {
    items,
    subtotalCentavos,
    subtotal: centavosToPesos(subtotalCentavos),
    // Recorded on the order, carried onto the invoice rather than assumed.
    priceCurrency: typeof order.priceCurrency === "string" ? order.priceCurrency : PRICE_CURRENCY,
    // The convention THIS invoice is computed under: the confirmed rule that
    // prices are VAT-inclusive (pricingConfig.js) — for every invoice computed
    // from now on, including one for an order placed before the rule, whose own
    // recorded flag is left untouched. A draft saved under the old convention
    // no longer matches this base, so it cannot be issued until it is re-saved
    // (and recomputed); an already-issued invoice is never recomputed.
    priceIsVatInclusive: PRICES_INCLUDE_VAT,
    pricingVersion: PRICING_VERSION,
    // True only when every line carries a VAT snapshot (orders created with
    // per-item classification). Partial snapshots are not itemized.
    itemizedVat: items.every((i) => i.vatClassification !== null),
  };
}

/**
 * Split an invoice discount between VATable and VAT-Exempt sales in proportion
 * to their gross amounts, in whole centavos. Each share is floored; the at
 * most one leftover centavo goes to the LARGER share (VATable on a tie). The
 * shares always sum to the discount exactly and never exceed their own gross.
 * BigInt keeps discount × gross exact however large the figures are.
 */
function allocateDiscountCentavos({ vatableGrossCentavos, vatExemptGrossCentavos, discountCentavos }) {
  const total = vatableGrossCentavos + vatExemptGrossCentavos;
  if (discountCentavos === 0 || total === 0) return { vatableCentavos: 0, vatExemptCentavos: 0 };
  const d = BigInt(discountCentavos);
  const t = BigInt(total);
  let vatableCentavos = Number((d * BigInt(vatableGrossCentavos)) / t);
  let vatExemptCentavos = Number((d * BigInt(vatExemptGrossCentavos)) / t);
  const remainder = discountCentavos - vatableCentavos - vatExemptCentavos;
  if (vatableGrossCentavos >= vatExemptGrossCentavos) vatableCentavos += remainder;
  else vatExemptCentavos += remainder;
  return { vatableCentavos, vatExemptCentavos };
}

/**
 * The admin's explicit adjustments.
 *
 * These are the only money figures a caller may supply, and each one is its own
 * named field. None of them touches a unit price: a discount reduces the net,
 * it does not restate what a vial cost, and the base subtotal on the stored
 * invoice stays exactly what the order said.
 */
function validateAdjustments(raw, subtotalCentavos, { itemizedVat = false } = {}) {
  const input = raw && typeof raw === "object" && !Array.isArray(raw) ? raw : {};

  const allowed = ["discountCentavos", "otherChargesCentavos", "withholdingTaxCentavos", "vatClassification"];
  for (const key of Object.keys(input)) {
    if (!allowed.includes(key)) {
      throw new PolicyError("unknown-field", `Adjustments cannot carry "${key}".`);
    }
  }

  const read = (key) => {
    const value = input[key];
    if (value === undefined || value === null) return 0;
    if (!readCentavos(value)) {
      throw new PolicyError(
        "invalid-adjustment",
        "Discounts and charges must be whole centavos of zero or more."
      );
    }
    return value;
  };

  const discountCentavos = read("discountCentavos");
  const otherChargesCentavos = read("otherChargesCentavos");
  const withholdingTaxCentavos = read("withholdingTaxCentavos");

  // A discount larger than the goods would invert the bill. Refused rather than
  // clamped: silently flooring it at the subtotal would charge an amount the
  // admin did not enter.
  if (discountCentavos > subtotalCentavos) {
    throw new PolicyError(
      "discount-exceeds-subtotal",
      "A discount cannot be larger than the invoice subtotal.",
      { discountCentavos, subtotalCentavos }
    );
  }

  // An itemized order's VAT is decided by its items; whatever the caller sent
  // for the invoice-level classification is ignored, never applied. An order
  // without item snapshots keeps the Admin's choice — which must be explicit:
  // VAT is never invented for an amount nobody marked VATable.
  const vatClassification = itemizedVat ? ITEMIZED_VAT : input.vatClassification;
  if (!itemizedVat && (vatClassification === undefined || vatClassification === null)) {
    throw new PolicyError(
      "vat-classification-required",
      "Choose this invoice's VAT classification. The order's products are not classified."
    );
  }
  if (!itemizedVat && !VAT_CLASSIFICATIONS.includes(vatClassification)) {
    throw new PolicyError("invalid-adjustment", "That VAT classification is not recognised.");
  }

  return { discountCentavos, otherChargesCentavos, withholdingTaxCentavos, vatClassification };
}

/**
 * Invoice totals, in centavos, for VAT-INCLUSIVE prices (pricingConfig.js).
 *
 * The amount after any discount is VAT-inclusive. For a VATable invoice the
 * VAT is EXTRACTED from it — never added on top — so the total stays exactly
 * that amount (plus any other charges):
 *
 *   grossAfterDiscount = max(0, subtotal − discount)       (discount handling unchanged)
 *   VATable:  vat = round(grossAfterDiscount × 12 ÷ 112)    (half up, integers)
 *             net = grossAfterDiscount − vat                ("Amount: Net of VAT")
 *   exempt / zero-rated:  vat = 0, net = grossAfterDiscount
 *   grandTotal = net + vat + otherCharges  = grossAfterDiscount + otherCharges
 *
 * One rounding, on the aggregated VATable amount — the invoice's documented
 * policy. Mirrors computeInvoiceTotals in src/services/invoiceModel.js, which
 * is used for the editor's display and the legacy manual path.
 */
function computeInvoiceTotalsCentavos({ subtotalCentavos, adjustments, items = [] }) {
  const { discountCentavos, otherChargesCentavos, withholdingTaxCentavos, vatClassification } =
    adjustments;

  let netCentavos;
  let vatRate;
  let vatAmountCentavos;
  let vatableSalesCentavos;
  let vatExemptSalesCentavos;
  let zeroRatedSalesCentavos;

  if (vatClassification === ITEMIZED_VAT) {
    // Per-item VAT: sum each bucket from the line snapshots, then split the
    // discount pro-rata. Every line must carry a valid snapshot.
    let vatableGrossCentavos = 0;
    let vatExemptGrossCentavos = 0;
    for (const it of items) {
      const cls = readProductVatClassification(it?.vatClassification);
      if (!cls || !readCentavos(it?.lineTotalCentavos)) {
        throw new PolicyError(
          "order-snapshot-invalid",
          "This order's VAT classifications cannot be invoiced."
        );
      }
      if (cls === "vatable") vatableGrossCentavos += it.lineTotalCentavos;
      else vatExemptGrossCentavos += it.lineTotalCentavos;
    }
    if (vatableGrossCentavos + vatExemptGrossCentavos !== subtotalCentavos) {
      throw new PolicyError("order-snapshot-invalid", "This order's subtotal does not match its line items.");
    }
    const share = allocateDiscountCentavos({ vatableGrossCentavos, vatExemptGrossCentavos, discountCentavos });
    // Both buckets are VAT-inclusive amounts. VAT is extracted from the
    // VATable bucket once, on its aggregate (one rounding per invoice).
    const vatableAfterDiscountCentavos = vatableGrossCentavos - share.vatableCentavos;
    vatAmountCentavos = splitVatInclusiveCentavos(vatableAfterDiscountCentavos).vatCentavos;
    vatableSalesCentavos = vatableAfterDiscountCentavos - vatAmountCentavos; // net of VAT
    vatExemptSalesCentavos = vatExemptGrossCentavos - share.vatExemptCentavos;
    zeroRatedSalesCentavos = 0;
    netCentavos = vatableSalesCentavos + vatExemptSalesCentavos;
    vatRate = vatableAfterDiscountCentavos > 0 ? VAT_STANDARD_RATE : 0;
  } else {
    const grossAfterDiscountCentavos = Math.max(0, subtotalCentavos - discountCentavos);
    vatRate = vatClassification === "vatable" ? VAT_STANDARD_RATE : 0;
    vatAmountCentavos =
      vatClassification === "vatable" ? splitVatInclusiveCentavos(grossAfterDiscountCentavos).vatCentavos : 0;
    // The amount net of VAT (equal to the gross when no VAT applies).
    netCentavos = grossAfterDiscountCentavos - vatAmountCentavos;
    vatableSalesCentavos = vatClassification === "vatable" ? netCentavos : 0;
    vatExemptSalesCentavos = vatClassification === "vat_exempt" ? netCentavos : 0;
    zeroRatedSalesCentavos = vatClassification === "zero_rated" ? netCentavos : 0;
  }

  const grandTotalCentavos = netCentavos + vatAmountCentavos + otherChargesCentavos;
  const totalSalesVatInclusiveCentavos = netCentavos + vatAmountCentavos;
  const totalAmountDueCentavos = grandTotalCentavos - withholdingTaxCentavos;

  for (const value of [grandTotalCentavos, totalAmountDueCentavos]) {
    if (!Number.isSafeInteger(value)) {
      throw new PolicyError(
        "invoice-total-out-of-range",
        "This invoice's total is too large to record accurately."
      );
    }
  }

  return {
    netCentavos,
    vatRate,
    vatableSalesCentavos,
    vatExemptSalesCentavos,
    zeroRatedSalesCentavos,
    vatAmountCentavos,
    grandTotalCentavos,
    totalSalesVatInclusiveCentavos,
    totalAmountDueCentavos,
  };
}

/** Presentation text: allowlisted, string-only, bounded. Never money. */
function validatePresentation(raw) {
  const input = raw && typeof raw === "object" && !Array.isArray(raw) ? raw : {};
  const out = {};
  for (const key of Object.keys(input)) {
    if (!PRESENTATION_FIELDS.includes(key)) {
      throw new PolicyError("unknown-field", `An invoice cannot carry "${key}" as presentation.`);
    }
    const value = input[key];
    if (value === undefined || value === null) continue;
    if (typeof value !== "string") {
      throw new PolicyError("invalid-presentation", `"${key}" must be text.`);
    }
    if (value.length > MAX_PRESENTATION_LENGTH) {
      throw new PolicyError("invalid-presentation", `"${key}" is too long.`);
    }
    out[key] = value;
  }
  for (const key of PRESENTATION_FIELDS) {
    if (!(key in out)) out[key] = "";
  }
  return out;
}

/**
 * Does a STORED invoice still carry the order's base pricing?
 *
 * Used at issue time, and as a tamper check on anything that reached the
 * document by another route. Compares only base pricing — adjustments are the
 * admin's and are expected to differ from one save to the next.
 */
function baseMatchesOrder(invoice, base) {
  const items = Array.isArray(invoice?.items) ? invoice.items : [];
  if (items.length !== base.items.length) return false;

  for (let i = 0; i < items.length; i += 1) {
    const stored = items[i];
    const expected = base.items[i];
    if (
      stored?.inventoryId !== expected.inventoryId ||
      stored?.quantity !== expected.quantity ||
      stored?.unitPriceCentavos !== expected.unitPriceCentavos ||
      stored?.lineTotalCentavos !== expected.lineTotalCentavos ||
      (stored?.vatClassification ?? null) !== (expected.vatClassification ?? null)
    ) {
      return false;
    }
  }

  return (
    invoice?.subtotalCentavos === base.subtotalCentavos &&
    invoice?.priceCurrency === base.priceCurrency &&
    invoice?.priceIsVatInclusive === base.priceIsVatInclusive &&
    invoice?.pricingVersion === base.pricingVersion
  );
}

module.exports = {
  VAT_STANDARD_RATE,
  VAT_CLASSIFICATIONS,
  ITEMIZED_VAT,
  allocateDiscountCentavos,
  PRESENTATION_FIELDS,
  MAX_PRESENTATION_LENGTH,
  isServerPricedOrder,
  readCentavos,
  centavosToPesos,
  buildInvoiceBaseFromOrder,
  validateAdjustments,
  computeInvoiceTotalsCentavos,
  validatePresentation,
  baseMatchesOrder,
};
