"use strict";

/**
 * Invoice base pricing, derived from an order's immutable snapshot.
 *
 * Pure: no Firestore, no Functions SDK. Everything that decides what an invoice
 * line COSTS lives here, so it is unit-testable without an emulator, and so
 * there is exactly one implementation of the arithmetic rather than one on each
 * side of the wire.
 *
 * THE AUTHORITY BOUNDARY
 *   Base pricing — item identity, quantity, unitPriceCentavos, lineTotalCentavos,
 *   subtotalCentavos, currency and the VAT convention — comes from the ORDER and
 *   from nowhere else. The caller cannot supply, override or influence any of it.
 *
 *   Adjustments — discount, other charges, withholding tax and the VAT
 *   classification — are genuinely the admin's decision, so they ARE accepted
 *   from the caller. They are separate fields that sit alongside the base and
 *   can never overwrite it: a discount reduces the net, it does not restate what
 *   a vial cost.
 *
 * Legacy orders (no pricingVersion) never reach this module. They keep the
 * manual invoice-time pricing they have always had.
 */

const { PRICING_VERSION, PRICE_CURRENCY, PRICE_IS_VAT_INCLUSIVE, PolicyError } = require("./policy");

/** Philippine VAT. Must stay identical to VAT_STANDARD_RATE in invoiceModel.js. */
const VAT_STANDARD_RATE = 12;
const VAT_CLASSIFICATIONS = Object.freeze(["vatable", "vat_exempt", "zero_rated"]);

/**
 * Free-text fields an admin genuinely owns.
 *
 * An allowlist rather than a denylist: a new field added to the editor must be
 * named here deliberately, so a caller can never smuggle `subtotalCentavos`
 * through as "presentation" simply because nobody thought to forbid it.
 */
const PRESENTATION_FIELDS = Object.freeze([
  "customerName", "registeredName", "customerAddress", "customerContact",
  "customerTin", "customerCode", "shipTo",
  "salesRepName", "salesRepCode",
  "invoiceDate", "saleType", "purchaseOrderNumber", "referenceNumber",
  "vaccinesTemp",
  "companyName", "companyAddress", "companyContact", "companyTin",
  "paymentTerms", "deliveryTerms", "notes", "remarks",
  "processedBy", "packedBy", "deliveredBy", "preparedBy", "checkedBy",
  "approvedBy", "receivedBy", "authorizedRepresentative",
  "customerAcknowledgment", "soloParentId", "bookletInfo",
  "atpNumber", "atpDate", "printerBlock", "accreditationNo", "accreditationDates",
]);

const MAX_PRESENTATION_LENGTH = 500;

/** An order whose prices were generated by the server. Version stamp only. */
function isServerPricedOrder(order) {
  return order?.pricingVersion === PRICING_VERSION;
}

/** A stored money figure: an exactly-representable non-negative integer. */
function readCentavos(value) {
  return (
    typeof value === "number" &&
    Number.isInteger(value) &&
    Number.isSafeInteger(value) &&
    value >= 0
  );
}

function centavosToPesos(centavos) {
  return Math.round(centavos) / 100;
}

/**
 * The invoice's base pricing, computed from the order snapshot.
 *
 * Every figure is RE-DERIVED here and cross-checked against what the order
 * recorded, so a corrupted order document produces a refusal rather than a
 * plausible-looking invoice. Nothing in the returned object came from a caller.
 */
function buildInvoiceBaseFromOrder(order) {
  if (!isServerPricedOrder(order)) {
    throw new PolicyError(
      "order-not-priced",
      "This order has no server price snapshot. It is invoiced through the manual path."
    );
  }
  const orderItems = Array.isArray(order.items) ? order.items : [];
  if (orderItems.length === 0) {
    throw new PolicyError(
      "order-has-no-items",
      "This order has no items to invoice."
    );
  }

  let subtotalCentavos = 0;
  const items = orderItems.map((it, index) => {
    const quantity = it?.quantity;
    if (typeof quantity !== "number" || !Number.isInteger(quantity) || quantity <= 0) {
      throw new PolicyError("order-snapshot-invalid", "This order's quantities cannot be invoiced.", {
        line: index,
      });
    }
    if (!readCentavos(it?.unitPriceCentavos) || it.unitPriceCentavos <= 0) {
      throw new PolicyError("order-snapshot-invalid", "This order's prices cannot be invoiced.", {
        line: index,
      });
    }
    // Recomputed, then compared with what the order stored. Trusting the stored
    // line total would let a single tampered field flow straight onto a bill.
    const lineTotalCentavos = quantity * it.unitPriceCentavos;
    if (!Number.isSafeInteger(lineTotalCentavos)) {
      throw new PolicyError("order-snapshot-invalid", "This order's totals are out of range.", {
        line: index,
      });
    }
    if (it.lineTotalCentavos !== lineTotalCentavos) {
      throw new PolicyError(
        "order-snapshot-invalid",
        "This order's line totals do not match its prices and quantities.",
        { line: index }
      );
    }
    subtotalCentavos += lineTotalCentavos;

    return {
      // Identity, carried through so an invoice line is traceable to a batch.
      orderItemId: null,
      inventoryId: typeof it.inventoryId === "string" ? it.inventoryId : null,
      batchId: typeof it.batchId === "string" ? it.batchId : "",
      vaccineName: typeof it.name === "string" ? it.name : "",
      itemDescription: typeof it.name === "string" ? it.name : "",
      expiry: "",
      quantity,
      unit: typeof order.unit === "string" && order.unit ? order.unit : "vials",
      unitPriceCentavos: it.unitPriceCentavos,
      lineTotalCentavos,
      // Peso mirrors for the print template, derived — never authoritative.
      unitPrice: centavosToPesos(it.unitPriceCentavos),
      amount: centavosToPesos(lineTotalCentavos),
    };
  });

  if (!Number.isSafeInteger(subtotalCentavos)) {
    throw new PolicyError("order-snapshot-invalid", "This order's subtotal is out of range.");
  }
  // The order recorded its own subtotal at reservation time. If the two ever
  // disagree, something rewrote one of them and neither can be trusted.
  if (order.subtotalCentavos !== subtotalCentavos) {
    throw new PolicyError(
      "order-snapshot-invalid",
      "This order's subtotal does not match its line items."
    );
  }

  return {
    items,
    subtotalCentavos,
    subtotal: centavosToPesos(subtotalCentavos),
    // Recorded on the order, carried onto the invoice rather than assumed.
    priceCurrency: typeof order.priceCurrency === "string" ? order.priceCurrency : PRICE_CURRENCY,
    priceIsVatInclusive:
      typeof order.priceIsVatInclusive === "boolean"
        ? order.priceIsVatInclusive
        : PRICE_IS_VAT_INCLUSIVE,
    pricingVersion: PRICING_VERSION,
  };
}

/**
 * The admin's explicit adjustments.
 *
 * These are the only money figures a caller may supply, and each one is its own
 * named field. None of them touches a unit price: a discount reduces the net,
 * it does not restate what a vial cost, and the base subtotal on the stored
 * invoice stays exactly what the order said.
 */
function validateAdjustments(raw, subtotalCentavos) {
  const input = raw && typeof raw === "object" && !Array.isArray(raw) ? raw : {};

  const allowed = ["discountCentavos", "otherChargesCentavos", "withholdingTaxCentavos", "vatClassification"];
  for (const key of Object.keys(input)) {
    if (!allowed.includes(key)) {
      throw new PolicyError("unknown-field", `Adjustments cannot carry "${key}".`);
    }
  }

  const read = (key) => {
    const value = input[key];
    if (value === undefined || value === null) return 0;
    if (!readCentavos(value)) {
      throw new PolicyError(
        "invalid-adjustment",
        "Discounts and charges must be whole centavos of zero or more."
      );
    }
    return value;
  };

  const discountCentavos = read("discountCentavos");
  const otherChargesCentavos = read("otherChargesCentavos");
  const withholdingTaxCentavos = read("withholdingTaxCentavos");

  // A discount larger than the goods would invert the bill. Refused rather than
  // clamped: silently flooring it at the subtotal would charge an amount the
  // admin did not enter.
  if (discountCentavos > subtotalCentavos) {
    throw new PolicyError(
      "discount-exceeds-subtotal",
      "A discount cannot be larger than the invoice subtotal.",
      { discountCentavos, subtotalCentavos }
    );
  }

  const vatClassification = input.vatClassification ?? "vatable";
  if (!VAT_CLASSIFICATIONS.includes(vatClassification)) {
    throw new PolicyError("invalid-adjustment", "That VAT classification is not recognised.");
  }

  return { discountCentavos, otherChargesCentavos, withholdingTaxCentavos, vatClassification };
}

/**
 * VAT-exclusive invoice totals, in centavos.
 *
 * Mirrors computeVatExclusiveTotals in src/services/invoiceModel.js exactly,
 * but in integers. The ONE rounding in the whole system is the VAT line —
 * 12% of an odd centavo figure is not itself a whole centavo — and it rounds
 * half up, stated here rather than left to whichever float path got there first.
 */
function computeInvoiceTotalsCentavos({ subtotalCentavos, adjustments }) {
  const { discountCentavos, otherChargesCentavos, withholdingTaxCentavos, vatClassification } =
    adjustments;

  const netCentavos = Math.max(0, subtotalCentavos - discountCentavos);
  const vatRate = vatClassification === "vatable" ? VAT_STANDARD_RATE : 0;
  const vatableSalesCentavos = vatClassification === "vatable" ? netCentavos : 0;
  const vatExemptSalesCentavos = vatClassification === "vat_exempt" ? netCentavos : 0;
  const zeroRatedSalesCentavos = vatClassification === "zero_rated" ? netCentavos : 0;

  // `vatableSalesCentavos` is already 0 for the exempt and zero-rated cases, so
  // this one expression covers all three without branching on the rate.
  const vatAmountCentavos = Math.round((vatableSalesCentavos * VAT_STANDARD_RATE) / 100);

  const grandTotalCentavos = netCentavos + vatAmountCentavos + otherChargesCentavos;
  const totalSalesVatInclusiveCentavos = netCentavos + vatAmountCentavos;
  const totalAmountDueCentavos = grandTotalCentavos - withholdingTaxCentavos;

  for (const value of [grandTotalCentavos, totalAmountDueCentavos]) {
    if (!Number.isSafeInteger(value)) {
      throw new PolicyError(
        "invoice-total-out-of-range",
        "This invoice's total is too large to record accurately."
      );
    }
  }

  return {
    netCentavos,
    vatRate,
    vatableSalesCentavos,
    vatExemptSalesCentavos,
    zeroRatedSalesCentavos,
    vatAmountCentavos,
    grandTotalCentavos,
    totalSalesVatInclusiveCentavos,
    totalAmountDueCentavos,
  };
}

/** Presentation text: allowlisted, string-only, bounded. Never money. */
function validatePresentation(raw) {
  const input = raw && typeof raw === "object" && !Array.isArray(raw) ? raw : {};
  const out = {};
  for (const key of Object.keys(input)) {
    if (!PRESENTATION_FIELDS.includes(key)) {
      throw new PolicyError("unknown-field", `An invoice cannot carry "${key}" as presentation.`);
    }
    const value = input[key];
    if (value === undefined || value === null) continue;
    if (typeof value !== "string") {
      throw new PolicyError("invalid-presentation", `"${key}" must be text.`);
    }
    if (value.length > MAX_PRESENTATION_LENGTH) {
      throw new PolicyError("invalid-presentation", `"${key}" is too long.`);
    }
    out[key] = value;
  }
  for (const key of PRESENTATION_FIELDS) {
    if (!(key in out)) out[key] = "";
  }
  return out;
}

/**
 * Does a STORED invoice still carry the order's base pricing?
 *
 * Used at issue time, and as a tamper check on anything that reached the
 * document by another route. Compares only base pricing — adjustments are the
 * admin's and are expected to differ from one save to the next.
 */
function baseMatchesOrder(invoice, base) {
  const items = Array.isArray(invoice?.items) ? invoice.items : [];
  if (items.length !== base.items.length) return false;

  for (let i = 0; i < items.length; i += 1) {
    const stored = items[i];
    const expected = base.items[i];
    if (
      stored?.inventoryId !== expected.inventoryId ||
      stored?.quantity !== expected.quantity ||
      stored?.unitPriceCentavos !== expected.unitPriceCentavos ||
      stored?.lineTotalCentavos !== expected.lineTotalCentavos
    ) {
      return false;
    }
  }

  return (
    invoice?.subtotalCentavos === base.subtotalCentavos &&
    invoice?.priceCurrency === base.priceCurrency &&
    invoice?.priceIsVatInclusive === base.priceIsVatInclusive &&
    invoice?.pricingVersion === base.pricingVersion
  );
}

module.exports = {
  VAT_STANDARD_RATE,
  VAT_CLASSIFICATIONS,
  PRESENTATION_FIELDS,
  MAX_PRESENTATION_LENGTH,
  isServerPricedOrder,
  readCentavos,
  centavosToPesos,
  buildInvoiceBaseFromOrder,
  validateAdjustments,
  computeInvoiceTotalsCentavos,
  validatePresentation,
  baseMatchesOrder,
};
