import 'package:latlong2/latlong.dart';
import 'package:intl/intl.dart';

/// Route display helpers for the Rider map. The route polyline + distance +
/// duration are generated by the web Dispatcher (OpenRouteService) and read
/// from Firestore — the Rider app only decodes and formats them for display.

/// Decode a Google/OpenRouteService encoded polyline (precision 5) into points.
/// Self-contained (no @mapbox/polyline-equivalent package). Returns an empty
/// list for null/empty/invalid input so callers can guard with `.length > 1`.
List<LatLng> decodePolyline(String? encoded, {int precision = 5}) {
  if (encoded == null || encoded.isEmpty) return const [];
  final List<LatLng> points = [];
  final double factor = precision == 6 ? 1e6 : 1e5;
  int index = 0;
  int lat = 0;
  int lng = 0;

  try {
    while (index < encoded.length) {
      int result = 0;
      int shift = 0;
      int b;
      do {
        b = encoded.codeUnitAt(index++) - 63;
        result |= (b & 0x1f) << shift;
        shift += 5;
      } while (b >= 0x20);
      lat += (result & 1) != 0 ? ~(result >> 1) : (result >> 1);

      result = 0;
      shift = 0;
      do {
        b = encoded.codeUnitAt(index++) - 63;
        result |= (b & 0x1f) << shift;
        shift += 5;
      } while (b >= 0x20);
      lng += (result & 1) != 0 ? ~(result >> 1) : (result >> 1);

      points.add(LatLng(lat / factor, lng / factor));
    }
  } catch (_) {
    // Malformed polyline — return whatever decoded cleanly (never throw).
  }
  return points;
}

/// "4.2 km" / "850 m"
String formatDistance(int? meters) {
  if (meters == null || meters <= 0) return '—';
  return meters >= 1000
      ? '${(meters / 1000).toStringAsFixed(1)} km'
      : '$meters m';
}

/// "23 min" / "1 h 5 min" / "45 s"
String formatDuration(int? seconds) {
  if (seconds == null || seconds <= 0) return '—';
  if (seconds < 60) return '$seconds s';
  final minutes = (seconds / 60).round();
  if (minutes < 60) return '$minutes min';
  final hours = minutes ~/ 60;
  final rem = minutes % 60;
  return rem > 0 ? '$hours h $rem min' : '$hours h';
}

/// Live arrival ETA = generatedAt + durationSeconds, formatted as a clock time
/// (e.g. "3:45 PM"). Falls back to the stored [etaText] snapshot when the
/// generation time isn't available.
String formatEta(DateTime? generatedAt, int? durationSeconds, String? etaText) {
  if (generatedAt != null && durationSeconds != null && durationSeconds > 0) {
    final eta = generatedAt.add(Duration(seconds: durationSeconds));
    return DateFormat('h:mm a').format(eta);
  }
  return (etaText != null && etaText.isNotEmpty) ? etaText : '—';
}
